### ISSUE TITLE
Remove contact form from website

### ISSUE THREAD

**Issue by pgleeson** [ModECI/Website#44]
Form at http://modeci.org/#contactPage is being used to spam us. Hasn't really been used for general contact requests...
Should be removed, and replaced by existing link to GH Discussions as well as "To contact the ModECI investigators directly please mail info - at - modeci.org".

Source https://github.com/ModECI/Website/blob/main/_includes/contact.html

Website can be tested locally with `jekyll serve`

@Ivy8127

**Comment by Ivy8127** [comment]
Made the changes however, Jekyll serve is throwing a webrick error, that I'm debugging. I haven't worked with an SSG like Jekyll before, so I might need a little bit more time to fix this. I also can't locate the Gemfile within the project.

**Comment by pgleeson** [comment]
Ok, great. I don't recall how I set up my environment for that I'm afraid. Maybe try some of the simple standard jekyll examples to test your local environment...

**Comment by Ivy8127** [comment]
Ah alright, I'll figure it out soon

> Ok, great. I don't recall how I set up my environment for that I'm afraid. Maybe try some of the simple standard jekyll examples to test your local environment...

**Comment by Ivy8127** [comment]
Good morning @pgleeson ... the error is stemming from not having the Gemfile on my local machine, I noticed that the Gemfile.lock file on Github is on the .gitignore file. Should I just create a new Gemfile within my local env, with new version dependencies or will that break the site?

**Comment by pgleeson** [comment]
@Ivy8127 I did have a Gemfile.lock locally, but it ran fine without it. I also tried in a fresh Docker container with:

```
apt-get install ruby-full build-essential zlib1g-dev
gem install jekyll bundler
git clone https://github.com/ModECI/Website
cd Website/
jekyll serve
```
and it ran fine without creating a Gemfile.lock or Gemfile, so not sure what the issue on your side is...

**Comment by Ivy8127** [comment]
> @Ivy8127 I did have a Gemfile.lock locally, but it ran fine without it. I also tried in a fresh Docker container with:
> 
> ```
> apt-get install ruby-full build-essential zlib1g-dev
> gem install jekyll bundler
> git clone https://github.com/ModECI/Website
> cd Website/
> jekyll serve
> ```
> 
> and it ran fine without creating a Gemfile.lock or Gemfile, so not sure what the issue on your side is...

Perhaps it might be because I'm running it on Windows and not on Linux?

**Comment by pgleeson** [comment]
Done in #45. Thanks @Ivy8127!
